site_name: Mava docs
site_description: Mava
site_author: Mava Contributors
repo_name: instadeep/Mava
repo_url: https://github.com/instadeepai/Mava
strict: false


theme:
  name: "material"
  language: en
  palette:
      primary: red
      accent: teal
  font:
    text: Avenir Next
  features:
    - navigation.tracking

plugins:
- search
- git-revision-date
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        rendering:
          show_source: true



markdown_extensions:
  - pymdownx.snippets:
      base_path: ./

  - pymdownx.pathconverter:
      base_path: ./
      relative_path: docs

nav:
  - Home: index.md
  - Systems:
    - General: systems/general.md
    - Tensorflow:
      - maddpg: systems/tf/maddpg.md
      - mad4pg: systems/tf/mad4pg.md
      - mappo: systems/tf/mappo.md
      - madqn: systems/tf/madqn.md
      - vdn and qmix: systems/tf/value_decomposition.md
  - Environments:
    - General: environments/general.md
    - Supported Environments:
      - Debugging Env: environments/debugging.md
      - PettingZoo: environments/pettingzoo.md
      - SMAC: environments/smac.md
      - Flatland: environments/flatland.md
      - Robocup: environments/robocup.md
      - Melting Pot: environments/meltingpot.md
      - Open Spiel: environments/open_spiel.md
  - Examples: examples.md
  - Extra:
    - Troubleshooting and Frequently Asked Questions: TROUBLESHOOTING.md
    - How to add docs: add_doc.md
